export const AUTH_SIGNIN_START = "AUTH_SIGNIN_START";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_FAIL = "AUTH_SIGNIN_FAIL";

export const AUTH_AUTOLOGIN_START = "AUTH_AUTOLOGIN_START";
export const AUTH_AUTOLOGIN_SUCCESS = "AUTH_AUTOLOGIN_SUCCESS";
export const AUTH_AUTOLOGIN_FAIL = "AUTH_AUTOLOGIN_FAIL";

export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const CLEAN_UP_AUTH_STATE = "CLEAN_UP_AUTH_STATE";

export const SIGN_OUT = "SIGN_OUT";
