export const GET_LATEST_NEWS_START = "GET_LATEST_NEWS_START";
export const GET_LATEST_NEWS_SUCCESS = "GET_LATEST_NEWS_SUCCESS";
export const GET_LATEST_NEWS_FAIL = "GET_LATEST_NEWS_FAIL";

export const POST_LATEST_NEWS_START = "POST_LATEST_NEWS_START";
export const POST_LATEST_NEWS_SUCCESS = "POST_LATEST_NEWS_SUCCESS";
export const POST_LATEST_NEWS_FAIL = "POST_LATEST_NEWS_FAIL";

export const CLEAR_POST_NEWS_STATE = "CLEAR_POST_NEWS_STATE";

export const GET_MYPOSTS_START = "GET_MYPOSTS_START";
export const GET_MYPOSTS_SUCCESS = "GET_MYPOSTS_SUCCESS";
export const GET_MYPOSTS_FAIL = "GET_MYPOSTS_FAIL";

export const DELETE_NEWS_START = "DELETE_NEWS_START";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAIL = "DELETE_NEWS_FAIL";
